import Head from 'next/head'
import Image from 'next/image'
import reducer, { initialState } from '../context-api/reducer'
import { StateProvider } from '../context-api/StateProvider'
import Board from '../modules/Board/Board'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <StateProvider
      initialState={initialState}
      reducer={reducer}
    >
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="#">Tasktion!</a>
        </h1>
        <Board/>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Made by{' '}
          <span className={styles.logo}>
          <a href="https://twitter.com/khanasif41" target="_blank" rel="noopener noreferrer">@asifkhan0410</a>
          </span>
        </a>
      </footer>
    </div>
    </StateProvider>
  )
}
